### PR TITLE
Add 481050, Various Photos

### PR DESCRIPTION
**Pull request by Phaeton**
## Describe your changes

Add 481050, Various Photos]

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] I have considered reviewing any of the other [open pull requests](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) so that pull requests get merged faster.

### CODE REVIEW

**Comment by dziban303** [comment]
Looks good

**Comment by rickstaa** [comment]
> Looks good

@dziban303 Thanks for your review. Really helps!

**Comment by rickstaa** [comment]
Replaced by https://github.com/sdr-enthusiasts/plane-alert-db/pull/157 since this PR was created when the actions were not yet finished.

**Comment by rickstaa** [comment]
Merged into main through #157. Thanks for your contribution.

**Pull request closed without merging**
