### PR TITLE
Update plane-alert-db.csv

### PR DESCRIPTION
**Pull request by kotahukka**
Added more aircraft.  Mostly from the Houston TX area

## Describe your changes

PLANE INFO: For the helicopters, some pulled from here https://www.helis.com/database/org/Texas-Helicopters/, Hermann Life flight observed personally from seeing them at scenes of vehicle accidents.  The wildfire aircraft was from observing them over a recent wildfire via flightaware.  Houston Police and Harris County Sheriff were captured on my feeder.

## Checklist before requesting a review

- [x ] I have performed a self-review of my code.
- [None to check ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

### CODE REVIEW

**Review by dziban303 — CHANGES_REQUESTED** [review]
Thanks for the submission but this is unusable. Looks like you edited it in excel, which changes a lot of the icao hexes into nonsense, like 4408E8 into 4.41E+11 because it thinks the hexadecimal E means it's an exponent. When I get to a PC I'll look at importing the actual additions in via VS Code.

**Comment by kotahukka** [comment]
Dang I missed that.  Yes I did edit in excel.  You can reject it and I’ll fix it tomorrow. I’m about to head into work.

**Comment by dziban303** [comment]
I've had a look through just the additions at the end and there are some problems. Cosmetic things like Excel changing LLC to Llc. Some of the ICAO type codes were wrong, like the Canadair tankers are CL2T rather than CL215. Planefence/planealert won't show the right silhouette picture without the right codes so that's important. Also at least some of this info is very outdated, like the last one:
```j
AD7D0E,N9686F,Houston Police Department,Stearman Kaydet,ST75,Pol,Police Squad,The Cops,Copper Chopper,Police Forces,https://en.wikipedia.org/wiki/Boeing-Stearman_Model_75
```

First, it'd be kinda weird for the Houston Police to have a Stearman biplane! According to the [FAA](https://registry.faa.gov/AircraftInquiry/Search/NNumberResult?nNumberTxt=N9686F), the HPD helicopter with that N-number was deregistered in 1991 after being destroyed (in a crash?) and the Stearman which now has that N-number is owned by a private individual in Mississippi.

Another is N8373F, which was apparently sold by the HPD in 2006 and now flies out of Utah. Presumably these came from Helis.com, which can be useful to fill in the blanks like with serial numbers, but probably shouldn't be used as a primary source. I didn't check every one of these so I don't know which of the others are correct or not. If you could check each of these with the FAA's N-number registry and Flightaware or Radarbox or FR24 to verify they're correct and current we can add them.

**Comment by Phaeton** [comment]
Closing as these changes were implemented with #293

**Pull request closed without merging**
