### PR TITLE
additional harrier, Correct pix for 0D088C, add C-2A ae0451

### PR DESCRIPTION
**Pull request by dziban303**
## Describe your changes

Additional harrier added

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

### CODE REVIEW

**Review by Phaeton — COMMENTED** [review]
Reviewed all but the `plane_images.txt` file as there were too many changes to render. Any thought why all lines were edited? Did you sort the file?

**Comment by dziban303** [comment]
I didn't touch the file at all, I just added the one harrier at the end of plane-alert-db.csv. The rest was done by the derivative database routine, I guess.

**Comment by dziban303** [comment]
a trivial check (i.e. I did not spend more than 5 minutes on it) with a previous version shows the same content in the same lines, just the additional hex added at the end. If the derivative routine wipes the file and then rewrites it in its entirety, or whatever was done to cause GH to think there were 12000+ changes, you'd have to ask the person who wrote the script why it did that, I have no idea.

**Comment by dziban303** [comment]
There is nothing wrong with the PR that I can see, just the usual script annoyances.

It really should not be this difficult to submit changes.

**Pull request closed without merging**
