### PR TITLE
Correct ACE463 Photos

### PR DESCRIPTION
**Pull request by Phaeton**
## Describe your changes
Correct ACE463 Photos that are currently incorrect

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

### CODE REVIEW

**Comment by Phaeton** [comment]
@rickstaa It looks like this pull request was incorrectly tagged with the `planes` label. Only `images` were updated.

**Comment by dziban303** [comment]
Well I can't find where to add an approval tag but it looks good to me

**Comment by Phaeton** [comment]
well, it seems if you add additional commits to an existing pull request, the invalid label is applied?

**Review by dziban303 — APPROVED** [review]
I found the approve thing 🎉

**Comment by dziban303** [comment]
> well, it seems if you add additional commits to an existing pull request, the invalid label is applied?

So is the 'correct' way of doing this to create a new branch in our own forks and merge those individually? I'm just used to committing everything to the main branch. I have no idea how to do a different fork in VSCode 😩

**Comment by rickstaa** [comment]
> > well, it seems if you add additional commits to an existing pull request, the invalid label is applied?
> 
> So is the 'correct' way of doing this to create a new branch in our own forks and merge those individually? I'm just used to committing everything to the main branch. I have no idea how to do a different fork in VSCode 😩

@dziban303 no, you and @Phaeton were using the correct way. The problems were caused by different line endings between Linux and Windows. I now changed the action 👍🏻.

**Pull request closed without merging**
