### PR TITLE
Added 250 Military AC

### PR DESCRIPTION
**Pull request by g0Idfinger**
## Describe your changes

PLANE INFO: Info pulled from my VRS DB since Jan 1,2024

### CODE REVIEW

**Comment by dziban303** [comment]
is this done? trying to figure out why it ran the derivative script before merging

**Comment by g0Idfinger** [comment]
I was going to ask how you ran that on my side but not your side?

**Comment by dziban303** [comment]
I didn't run anything. I think you have to disable the scripts on your end but @Phaeton is more familiar with it than me. I'm not sure if it'll affect a merge or not.

**Comment by g0Idfinger** [comment]
I thought I just ran the scripts locally to ensure there were no dupes or csv formating errors before my commit. I too, know enough to be dangerous and love to tinker. :P

**Comment by dziban303** [comment]
I didn't run anything. I think you have to disable the scripts on your end
but @phaeton is more familiar with it than me. I'm not sure if it'll affect
a merge or not.

**Comment by Phaeton** [comment]
@g0Idfinger In the future, make your changes in a branch, not in `main` and I would recommend not enabling the derivative script in your local instance. 

@dziban303 - did you review these changes?

**Comment by g0Idfinger** [comment]
I will make a branch today!

**Comment by Phaeton** [comment]
Closing, superseded by #492

**Pull request closed without merging**
