### PR TITLE
Update plane-alert-db.csv

### PR DESCRIPTION
**Pull request by bacco007**
Add a couple of Australian rescue aircraft + NSW State Government imagery/lidar plane

### CODE REVIEW

**Comment by Indr1d-C0ld** [comment]
> Add a couple of Australian rescue aircraft + NSW State Government imagery/lidar plane

Hello, and thanks for this interesting db - I would like to send you my personal one, maybe you can merge after check, when my station was up I've set up by scripts the adsb logging on CSV, and then on daily base I used to import in a spreadsheet with automatic cells colouring and other - I'm interested in 'exotic' and MilAir, so I've cut out only uninteresting private, business and commercial airlines. Feel free to let me know if can be of any help.

**Comment by Sportsbadger** [comment]
> Add a couple of Australian rescue aircraft + NSW State Government imagery/lidar plane

Hi, thank you so much for taking the time to add these planes. I often moan that no-one helps, and then I end up ignoring your contribution for nearly 2 months. Sorry. I've added your entries to my working list and I'll publish them in the next hour or so. If you have any more entries you would like add please go right ahead. Thank you once more.

**Comment by Sportsbadger** [comment]
> > Add a couple of Australian rescue aircraft + NSW State Government imagery/lidar plane
> 
> Hello, and thanks for this interesting db - I would like to send you my personal one, maybe you can merge after check, when my station was up I've set up by scripts the adsb logging on CSV, and then on daily base I used to import in a spreadsheet with automatic cells colouring and other - I'm interested in 'exotic' and MilAir, so I've cut out only uninteresting private, business and commercial airlines. Feel free to let me know if can be of any help.

Yes please ! The more data the better.

**Comment by Indr1d-C0ld** [comment]
> Yes please ! The more data the better.

So, where can I send my db? I can share privately the Google Spreadsheet link if you want, just let me know.

**Comment by Sportsbadger** [comment]
> > Yes please ! The more data the better.
> 
> So, where can I send my db? I can share privately the Google Spreadsheet link if you want, just let me know.

Hi, the easiest way to get hold of me (and lots of other nice people who like planes) is on the SDR enthusiasts Discord Page - https://discord.gg/sTf9uYF. And thank you for offering to share - I also do all my work on this list via G-sheets. Happy to share mine with you.  You can also email me at captain DOT vice AT gmail DOT com.

**Pull request closed without merging**
